# Generated by Django 3.1.6 on 2021-02-10 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_messages_text', models.TextField()),
                ('match_dialog_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_dialog_id', to='match.match')),
                ('message_to_user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_to_user_id', to=settings.AUTH_USER_MODEL)),
                ('message_user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
