# Generated by Django 3.1.6 on 2021-02-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_to_user_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_user_id',
        ),
    ]
