# Generated by Django 3.1.6 on 2021-02-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_subscriber', models.CharField(choices=[('standart', 'standart'), ('vip', 'vip'), ('premium', 'premium')], default='standart', max_length=80, null=True, verbose_name='type_subscriber')),
            ],
        ),
    ]
