# Generated by Django 3.1.6 on 2021-02-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_subscriber', models.CharField(default='standart', max_length=80, verbose_name='type_subscriber')),
                ('swipes', models.IntegerField(default='20', verbose_name='swipes')),
                ('radius', models.IntegerField(default='10', verbose_name='radius')),
            ],
        ),
    ]
