# Generated by Django 3.1.6 on 2021-02-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='radius',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='swipes',
            field=models.IntegerField(null=True),
        ),
    ]
