# Generated by Django 3.1.6 on 2021-02-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20210211_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='status',
            new_name='first_person_status',
        ),
        migrations.AddField(
            model_name='match',
            name='second_person_status',
            field=models.BooleanField(default=False),
        ),
    ]
